global:
  scrape_interval: 15s
  evaluation_interval: 30s
scrape_configs:
  - job_name: "book-store-api"
    scrape_interval: 5s
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ["backend:8080"]
