apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: migration
          image: book-store-api:1.0.1
          imagePullPolicy: Never
          command: ["./migrate", "up"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
      containers:
        - name: backend
          image: book-store-api:1.0.1
          imagePullPolicy: Never
          command: ["./main"]
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: PORT
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: ENV
            - name: JWT_EXP
              valueFrom:
                configMapKeyRef:
                  name: backend-configmap
                  key: JWT_EXP
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY
          ports:
            - name: backend
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
