apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
spec:
  ports:
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
    - port: 55681
      targetPort: 55681
      name: otlp-http
  selector:
    app: otel-collector
