kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 3000 # Grafana
        hostPort: 3000
      - containerPort: 3100 # Loki
        hostPort: 3100
      - containerPort: 3200 # Tempo
        hostPort: 3200
      - containerPort: 9009 # Mimir
        hostPort: 9009
