apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: YWRtaW4K # "admin" codificado em Base64
  POSTGRES_PASSWORD: dW1hc2VuaGFtdWl0b2RpZmljaWw= # "umasenhamuitodificil" codificado em Base64
