apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzLnF1dWV4Zm9reXh3cWZ3bXpzbWtxOnVtYXNlbmhhbXVpdG9kaWZpY2lsQGF3cy0wLXVzLXdlc3QtMS5wb29sZXIuc3VwYWJhc2UuY29tOjU0MzIvcG9zdGdyZXM= # postgresql://postgres:umasenhamuitodificil@db.quuexfokyxwqfwmzsmkq.supabase.co:5432/postgres
  SECRET_KEY: VU1TRUNSRVRLRVlNVE9ESUZJQ0lM #UMSECRETKEYMTODIFICIL
