apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: app
  annotations:
    description: Configuration for backend application
data:
  PORT: "8080"
  ENV: "production"
  JWT_EXP: "604800"
