apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/api/v1/metrics"
    spec:
      initContainers:
        - name: migration
          image: book-store-api:1.0.1
          imagePullPolicy: Never
          command: ["./migrate", "up"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
      containers:
        - name: app
          image: book-store-api:1.0.1
          imagePullPolicy: Never
          command: ["./main"]
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: PORT
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: ENV
            - name: JWT_EXP
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: JWT_EXP
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
          ports:
            - containerPort: 8080
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
