apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: YWRtaW4= # "admin" codificado corretamente
  POSTGRES_PASSWORD: dW1hc2VuaGFtdWl0b2RpZmljaWw= # "umasenhamuitodificil" codificado corretamente
